/**
 * Full-fidelity email preview matching the reference design.
 *
 * Replaces the small EmailPreviewPane snippet for the right pane of the
 * subscription editor. Renders chrome (orange top bar + dealer header) plus
 * a body that adapts to the selected email type and currently-enabled
 * section toggles.
 */
import type { ReactNode } from "react";

type SectionMap = Record<string, boolean>;

type Props = {
  emailType: "daily" | "weekly" | "monthly" | "eoc";
  enabled: boolean;
  sections: SectionMap;
  dealerName: string;
  dealerAddress?: string;
  periodLabel: string;
};

const TYPE_TITLES: Record<string, string> = {
  daily: "Daily digest",
  weekly: "Weekly performance",
  monthly: "Monthly value report",
  eoc: "End-of-campaign report",
};

const TYPE_PERIOD_PREFIX: Record<string, string> = {
  daily: "Day of",
  weekly: "Week of",
  monthly: "Month of",
  eoc: "Campaign ending",
};

export function RichEmailPreview({
  emailType,
  enabled,
  sections,
  dealerName,
  periodLabel,
}: Props) {
  if (!enabled) {
    return (
      <div className="bg-surface-card border border-border-subtle rounded-xl shadow-sm overflow-hidden">
        <div className="h-1.5 bg-text-muted/30" />
        <div className="px-6 py-16 text-center">
          <h3 className="text-base font-semibold text-text-primary">
            {TYPE_TITLES[emailType]} is paused
          </h3>
          <p className="mt-2 text-sm text-text-secondary max-w-sm mx-auto">
            This recipient won't receive the {TYPE_TITLES[emailType].toLowerCase()}{" "}
            until it's reactivated in the schedule panel.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-surface-card border border-border-subtle rounded-xl shadow-sm overflow-hidden">
      {/* Orange accent bar */}
      <div className="h-1.5 bg-orange-500" />

      <div className="px-5 sm:px-7 pt-6 sm:pt-8 pb-6 sm:pb-8 space-y-6">
        {/* Header */}
        <div>
          <h2 className="text-xl sm:text-2xl font-bold leading-tight text-text-primary">
            {dealerName}
          </h2>
          <p className="text-sm text-text-secondary mt-1">
            {TYPE_PERIOD_PREFIX[emailType]} {periodLabel}
          </p>
        </div>

        <div className="border-b border-border-subtle" />

        {/* AI Insight */}
        {sections.ai_narrative !== false && (
          <AiInsightCard emailType={emailType} />
        )}

        {/* Body — different per email type */}
        {emailType === "weekly" && <WeeklyBody sections={sections} />}
        {emailType === "daily" && <DailyBody sections={sections} />}
        {emailType === "monthly" && <MonthlyBody sections={sections} />}
        {emailType === "eoc" && <EOCBody sections={sections} />}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// AI Insight
// ─────────────────────────────────────────────────────────────────────────────
function AiInsightCard({ emailType }: { emailType: string }) {
  const insight = INSIGHT_COPY[emailType] ?? "";
  return (
    <div className="bg-orange-50 border border-orange-200 rounded-lg px-4 py-4">
      <div className="text-[11px] font-bold uppercase tracking-wide text-orange-600">
        AI Insight ·{" "}
        <span className="text-orange-500 font-medium normal-case tracking-normal">
          Generated by Haiku 4.5
        </span>
      </div>
      <p className="mt-2 text-[13px] leading-relaxed text-text-primary">
        {insight}
      </p>
    </div>
  );
}

const INSIGHT_COPY: Record<string, string> = {
  weekly:
    "Honda DTLA handled 60 total calls this week — 18 of those after hours. After-hours calls resulted in 8 appointments set. The full-week funnel: 12 appointments set, 8 showed, 5 demo'd, and 3 closed. Ten hot leads received 24 outreach attempts. Callbacks were scheduled for 8 leads who weren't reachable on first contact.",
  daily:
    "Yesterday Vini handled 24 conversations and set 14 appointments — 4 of those came from after-hours coverage. Three SMS conversations are waiting for human takeover.",
  monthly:
    "This month Vini handled 1,420 unique customers across 2,956 conversations — equivalent to ~340 hours of BDC effort. 147 appointments booked, 47 lapsed customers re-engaged, and 63 booked after hours.",
  eoc:
    "Campaign reached 4,214 unique contacts and converted 634 to appointments (12.2%). SMS follow-ups drove the highest last-touch conversion at 41%; consider front-loading SMS earlier in the next cadence.",
};

// ─────────────────────────────────────────────────────────────────────────────
// Section primitive
// ─────────────────────────────────────────────────────────────────────────────
function SectionFrame({
  title,
  children,
  footer,
}: {
  title: string;
  children: ReactNode;
  footer?: ReactNode;
}) {
  return (
    <div className="bg-surface-background border border-border-subtle rounded-lg overflow-hidden">
      <div className="px-5 pt-4 pb-3">
        <div className="text-[11px] font-bold uppercase tracking-wide text-text-secondary">
          {title}
        </div>
      </div>
      <div className="px-5 pb-4">{children}</div>
      {footer && (
        <div className="px-5 pb-4 pt-2 border-t border-border-subtle text-[12px] text-text-secondary">
          {footer}
        </div>
      )}
    </div>
  );
}

function StatTile({
  value,
  sub,
  label,
}: {
  value: string;
  sub?: string;
  label: string;
}) {
  return (
    <div className="text-center sm:text-left">
      <div className="text-2xl sm:text-3xl font-bold tabular text-text-primary leading-none">
        {value}
        {sub && (
          <span className="ml-1 text-base text-text-secondary font-semibold">
            {sub}
          </span>
        )}
      </div>
      <div className="text-[12px] text-text-secondary mt-1.5">{label}</div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// WEEKLY body
// ─────────────────────────────────────────────────────────────────────────────
function WeeklyBody({ sections }: { sections: SectionMap }) {
  return (
    <>
      {sections.call_volume !== false && (
        <SectionFrame
          title="Call volume"
          footer={
            <div className="flex flex-wrap gap-x-4 gap-y-1">
              <span>
                After-hours appts:{" "}
                <span className="tabular font-semibold text-text-primary">12</span>
              </span>
              <span>
                No answer:{" "}
                <span className="tabular font-semibold text-text-primary">22</span>
              </span>
              <span>
                Callbacks:{" "}
                <span className="tabular font-semibold text-text-primary">8</span>
              </span>
            </div>
          }
        >
          <div className="grid grid-cols-3 gap-3 sm:gap-4 mt-1">
            <StatTile value="60" label="Total Calls" />
            <StatTile value="18" sub="(30%)" label="After Hours" />
            <StatTile value="42" label="Inbound" />
          </div>
        </SectionFrame>
      )}

      {sections.appointment_funnel !== false && (
        <SectionFrame
          title="Appointment funnel"
          footer={
            <div className="flex flex-wrap gap-x-4 gap-y-1">
              <span>
                Show rate:{" "}
                <span className="tabular font-semibold text-text-primary">67%</span>
              </span>
              <span>
                Close rate:{" "}
                <span className="tabular font-semibold text-text-primary">25%</span>
              </span>
            </div>
          }
        >
          <FunnelBars
            steps={[
              { count: 12, label: "Set", color: "bg-orange-500" },
              { count: 8, label: "Showed", color: "bg-orange-400" },
              { count: 5, label: "Demo'd", color: "bg-amber-400" },
              { count: 3, label: "Closed", color: "bg-emerald-500" },
            ]}
          />
        </SectionFrame>
      )}

      {sections.lead_activity !== false && (
        <SectionFrame title="Lead activity">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4">
            <StatTile value="5" label="Hot leads" />
            <StatTile value="19" label="Warm leads" />
            <StatTile value="24" label="Outreach attempts" />
            <StatTile value="2.4" label="Avg touches / lead" />
          </div>
        </SectionFrame>
      )}

      {sections.top_vehicles !== false && (
        <SectionFrame title="Top vehicles of interest">
          <ul className="divide-y divide-border-subtle">
            {[
              { name: "Honda Civic 2025", count: 18 },
              { name: "Honda CR-V 2025", count: 14 },
              { name: "Honda Pilot 2024", count: 9 },
              { name: "Honda Accord 2024", count: 7 },
            ].map((row) => (
              <li
                key={row.name}
                className="flex items-center justify-between py-2 text-sm"
              >
                <span className="text-text-primary">{row.name}</span>
                <span className="tabular font-semibold text-text-primary">
                  {row.count}
                </span>
              </li>
            ))}
          </ul>
        </SectionFrame>
      )}

      {sections.story !== false && (
        <SectionFrame title="Story of the week">
          <div className="flex items-start gap-3">
            <div className="h-9 w-9 shrink-0 rounded-full bg-orange-100 grid place-items-center text-orange-600 text-base">
              ★
            </div>
            <div>
              <div className="text-[11px] font-semibold uppercase tracking-wide text-orange-600">
                Saved after 6 turns
              </div>
              <p className="mt-1 text-[13px] leading-relaxed text-text-primary">
                A weeknight chat opened with a price objection. Across two
                follow-ups the next day, the agent narrowed term and trim to the
                customer's $390/month target — converting to a Saturday test drive
                on a third touch.
              </p>
            </div>
          </div>
        </SectionFrame>
      )}
    </>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// DAILY body
// ─────────────────────────────────────────────────────────────────────────────
function DailyBody({ sections }: { sections: SectionMap }) {
  return (
    <>
      {sections.hero !== false && (
        <SectionFrame title="Yesterday + MTD">
          <div className="grid grid-cols-2 gap-3 sm:gap-4">
            <StatTile value="14" label="Appointments yesterday" />
            <StatTile value="142" label="MTD" />
          </div>
        </SectionFrame>
      )}

      {sections.action_required !== false && (
        <SectionFrame title="Action required">
          <ul className="space-y-1.5 text-sm">
            <ActionRow count={3} label="SMS conversations awaiting takeover" />
            <ActionRow count={8} label="Appointments confirmed for today" />
            <ActionRow count={1} label="Failed bookings — manual create" />
            <ActionRow count={3} label="Customers asked for a specific salesperson" />
          </ul>
          <div className="mt-4">
            <PrimaryCTAInline label="Review 15 items" />
          </div>
        </SectionFrame>
      )}

      {sections.inbound_kpis !== false && (
        <SectionFrame title="Inbound activity">
          <div className="grid grid-cols-2 gap-3 sm:gap-4">
            <StatTile value="58" label="Unique leads" />
            <StatTile value="14" label="Appointments" />
          </div>
        </SectionFrame>
      )}

      {sections.top_vehicles !== false && (
        <SectionFrame title="Top vehicles of interest">
          <ul className="divide-y divide-border-subtle">
            {[
              { name: "Honda Civic 2025", count: 18 },
              { name: "Honda CR-V 2025", count: 14 },
              { name: "Honda Pilot 2024", count: 9 },
              { name: "Honda Accord 2024", count: 7 },
            ].map((row) => (
              <li
                key={row.name}
                className="flex items-center justify-between py-2 text-sm"
              >
                <span className="text-text-primary">{row.name}</span>
                <span className="tabular font-semibold text-text-primary">
                  {row.count}
                </span>
              </li>
            ))}
          </ul>
        </SectionFrame>
      )}

      {sections.outbound !== false && (
        <SectionFrame title="Outbound activity">
          <div className="grid grid-cols-3 gap-3 sm:gap-4">
            <StatTile value="84" label="Unique reached" />
            <StatTile value="38%" label="Connect rate" />
            <StatTile value="4" label="Appts set" />
          </div>
        </SectionFrame>
      )}

      {sections.after_hours !== false && (
        <SectionFrame title="After-hours coverage">
          <div className="grid grid-cols-2 gap-3 sm:gap-4">
            <StatTile value="11" label="Leads engaged" />
            <StatTile value="4" label="Appts booked" />
          </div>
        </SectionFrame>
      )}
    </>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// MONTHLY body
// ─────────────────────────────────────────────────────────────────────────────
function MonthlyBody({ sections }: { sections: SectionMap }) {
  return (
    <>
      {sections.hero !== false && (
        <SectionFrame title="Work delivered">
          <div className="grid grid-cols-3 gap-3 sm:gap-4">
            <StatTile value="1,420" label="Customers reached" />
            <StatTile value="147" label="Appointments" />
            <StatTile value="47" label="Lapsed re-engaged" />
          </div>
        </SectionFrame>
      )}

      {sections.kpi_grid !== false && (
        <SectionFrame
          title="Month at a glance"
          footer="MoM deltas vs. March"
        >
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 sm:gap-4">
            <StatTile value="1,420" label="Customers" />
            <StatTile value="147" label="Appts" />
            <StatTile value="63" label="After hours" />
            <StatTile value="47" label="Lapsed" />
            <StatTile value="52s" label="First contact" />
            <StatTile value="340h" label="BDC-hours" />
          </div>
        </SectionFrame>
      )}

      {sections.trend_chart !== false && (
        <SectionFrame title="6-month appointments trend">
          <TrendChart />
        </SectionFrame>
      )}

      {sections.stories !== false && (
        <SectionFrame title="Customer stories">
          <div className="space-y-3">
            <StoryRow badge="Highest-value path" text="Trade-in + Pilot Touring closed across 9 touches over 2 weeks." />
            <StoryRow badge="Saved after 6 turns" text="Price-objection chat converted to Saturday test drive on the LX trim." />
            <StoryRow badge="Best after-hours save" text="7:42 PM SMS landed a Saturday service booking from an 18-month silent customer." />
          </div>
        </SectionFrame>
      )}
    </>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// EOC body
// ─────────────────────────────────────────────────────────────────────────────
function EOCBody({ sections }: { sections: SectionMap }) {
  return (
    <>
      {sections.headline !== false && (
        <SectionFrame title="Campaign results">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4">
            <StatTile value="634" label="Appointments" />
            <StatTile value="5,200" label="Contactable" />
            <StatTile value="12.2%" label="Conversion" />
            <StatTile value="33%" label="Opt-in booked" />
          </div>
        </SectionFrame>
      )}

      {sections.funnel !== false && (
        <SectionFrame title="Reach funnel">
          <FunnelBars
            steps={[
              { count: 4214, label: "Reached", color: "bg-orange-500" },
              { count: 1928, label: "Engaged", color: "bg-orange-400" },
              { count: 634, label: "Booked", color: "bg-emerald-500" },
            ]}
          />
        </SectionFrame>
      )}

      {sections.multichannel !== false && (
        <SectionFrame title="Multichannel performance">
          <div className="grid grid-cols-3 gap-3 sm:gap-4">
            <StatTile value="42%" label="Call engagement" />
            <StatTile value="51%" label="SMS engagement" />
            <StatTile value="28%" label="Email engagement" />
          </div>
        </SectionFrame>
      )}

      {sections.objections !== false && (
        <SectionFrame title="Top exit intents">
          <ul className="divide-y divide-border-subtle">
            {[
              { name: "Not in market right now", count: 412 },
              { name: "Vehicle purchased elsewhere", count: 287 },
              { name: "Awaiting next model year", count: 198 },
              { name: "Price out of range", count: 84 },
            ].map((row) => (
              <li
                key={row.name}
                className="flex items-center justify-between py-2 text-sm"
              >
                <span className="text-text-primary">{row.name}</span>
                <span className="tabular font-semibold text-text-primary">
                  {row.count}
                </span>
              </li>
            ))}
          </ul>
        </SectionFrame>
      )}

      {sections.recommendations !== false && (
        <SectionFrame title="Recommendations">
          <ul className="space-y-2 text-sm text-text-primary leading-relaxed">
            <li className="flex items-start gap-2">
              <span className="text-orange-500 mt-0.5">→</span>
              <span>Front-load SMS earlier — highest last-touch conversion at 41%.</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-orange-500 mt-0.5">→</span>
              <span>Suppress "vehicle purchased elsewhere" segment from next campaign list.</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-orange-500 mt-0.5">→</span>
              <span>Civic outperforms portfolio by 4 points — increase Civic inventory allocation.</span>
            </li>
          </ul>
        </SectionFrame>
      )}
    </>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Funnel bars
// ─────────────────────────────────────────────────────────────────────────────
function FunnelBars({
  steps,
}: {
  steps: Array<{ count: number; label: string; color: string }>;
}) {
  return (
    <div className="flex items-stretch gap-1 sm:gap-2">
      {steps.map((step, i) => (
        <div key={step.label} className="flex-1 flex items-stretch">
          <div className="flex-1 flex flex-col">
            <div
              className={`${step.color} rounded-md flex items-center justify-center text-white font-bold tabular text-xl sm:text-2xl min-h-[56px]`}
            >
              {step.count.toLocaleString()}
            </div>
            <div className="text-center text-[12px] text-text-secondary mt-2">
              {step.label}
            </div>
          </div>
          {i < steps.length - 1 && (
            <div className="text-text-muted self-center px-1 sm:px-1.5 pb-6">→</div>
          )}
        </div>
      ))}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Trend chart — minimal SVG sparkline
// ─────────────────────────────────────────────────────────────────────────────
function TrendChart() {
  const data = [102, 115, 121, 128, 138, 147];
  const max = Math.max(...data);
  const labels = ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr"];
  return (
    <div>
      <div className="flex items-end gap-2 sm:gap-3 h-32">
        {data.map((v, i) => (
          <div key={i} className="flex-1 flex flex-col items-center justify-end">
            <div
              className="w-full bg-orange-500 rounded-t-sm"
              style={{ height: `${(v / max) * 100}%` }}
            />
            <div className="mt-2 text-[10px] text-text-secondary">
              {labels[i]}
            </div>
            <div className="text-[10px] font-semibold tabular text-text-primary">
              {v}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function ActionRow({ count, label }: { count: number; label: string }) {
  return (
    <li className="flex items-center gap-3">
      <span className="inline-flex items-center justify-center min-w-[28px] h-6 px-2 rounded-full bg-orange-100 text-orange-700 text-[12px] font-bold tabular">
        {count}
      </span>
      <span className="text-[13px] text-text-primary">{label}</span>
    </li>
  );
}

function StoryRow({ badge, text }: { badge: string; text: string }) {
  return (
    <div className="flex items-start gap-3">
      <div className="h-7 w-7 shrink-0 rounded-full bg-orange-100 grid place-items-center text-orange-600 text-sm">
        ★
      </div>
      <div className="flex-1 min-w-0">
        <div className="text-[11px] font-semibold uppercase tracking-wide text-orange-600">
          {badge}
        </div>
        <p className="mt-0.5 text-[13px] leading-relaxed text-text-primary">
          {text}
        </p>
      </div>
    </div>
  );
}

function PrimaryCTAInline({ label }: { label: string }) {
  return (
    <span className="inline-flex items-center bg-brand-primary text-white text-[12px] font-bold px-4 py-2 rounded-[6px]">
      {label}
    </span>
  );
}
